name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: ecamazon
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Set up environment variables
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpassword" >> $GITHUB_ENV
          echo "DB_DATABASE=ecamazon" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests with MySQL
        run: npm test
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_DATABASE: ecamazon
